#!/bin/sh

cd "$(dirname "$0")/.."

MODE=${MODE:-prod}  # default to production mode
ARGS="$"

#TODO make this run generic run-dev and move this script somewhere else
if [ "$MODE" = "dev" ]; then
  make cli-dev
else
  make cli-prod
fi

