FROM golang:1.24-alpine

RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app

EXPOSE 8080
EXPOSE 2345

CMD go build -gcflags="all=-N -l" -o main ./cmd/server && \
    dlv exec ./main --headless --listen=:2345 --api-version=2 --accept-multiclient --continue
